import React, { useEffect, useState } from 'react';
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, TextField, Typography } from '@mui/material';
import { Add, Delete, Edit, EventNote, TaskAlt } from '@mui/icons-material';
import { toast } from 'react-toastify';
import GlassShell from '../../components/GlassKit/GlassShell';
import { cabinetCardSx, formatDateTime, OfflineAlert, PagePagination, PageState, PrimaryButton } from '../../components/Client/CabinetUI';
import clientService from '../../services/clientService';
import { useTranslation } from '../../i18n';
import useOnlineStatus from '../../hooks/useOnlineStatus';

const EMPTY = { caseId: '', title: '', dueAt: '', reminderMinutes: 1440, source: 'manual' };
export const buildDeadlinePayload = (form, timezone) => ({
  title: form.title,
  source: form.source,
  dueAt: new Date(form.dueAt).toISOString(),
  timezone,
  reminders: [{ intervalMinutes: form.reminderMinutes, channel: 'in_app' }],
});
const DeadlinesPage = () => {
  const { t, language } = useTranslation(); const online = useOnlineStatus(); const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const [filter, setFilter] = useState('upcoming'); const [page, setPage] = useState(1); const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState(null); const [dialogOpen, setDialogOpen] = useState(false); const [confirmAction, setConfirmAction] = useState(null); const [cases, setCases] = useState([]); const [saving, setSaving] = useState(false);
  const [state, setState] = useState({ loading: true, error: null, deadlines: [], totalPages: 1 });
  const load = async () => { setState((s) => ({ ...s, loading: true, error: null })); try { const [d, c] = await Promise.all([clientService.cabinet.getDeadlines({ status: filter, page, limit: 30, timezone }), clientService.cabinet.getCases({ limit: 100 })]); setState({ loading: false, error: null, deadlines: d.deadlines.map((item) => ({ ...item, caseId: item.clientCaseId, case: item.clientCase })), totalPages: d.totalPages || 1 }); setCases(c.cases); } catch (error) { setState((s) => ({ ...s, loading: false, error })); } };
  useEffect(() => { load(); }, [filter, page]); // eslint-disable-line react-hooks/exhaustive-deps
  const close = () => { setDialogOpen(false); setEditing(null); setForm(EMPTY); };
  const open = (item = null) => { setEditing(item); setForm(item ? { caseId: item.caseId || item.clientCaseId, title: item.title, dueAt: (item.dueAt || item.date || '').slice(0, 16), reminderMinutes: item.reminders?.[0]?.intervalMinutes ?? 1440, source: item.source || 'manual' } : { ...EMPTY }); setDialogOpen(true); };
  const save = async () => { if (!form.caseId || !form.title || !form.dueAt) return; setSaving(true); try { const payload = buildDeadlinePayload(form, timezone); if (editing) await clientService.cabinet.updateDeadline(form.caseId, editing.id, payload); else await clientService.cabinet.createDeadline(form.caseId, payload); close(); await load(); } catch (e) { toast.error(e.response?.data?.error || t('common.error')); } finally { setSaving(false); } };
  const remove = async (item) => { try { await clientService.cabinet.deleteDeadline(item.caseId, item.id); await load(); } catch { toast.error(t('common.error')); } };
  const confirmMutation = async () => { const action = confirmAction; setConfirmAction(null); if (!action) return; if (action.type === 'complete') { try { await clientService.cabinet.completeDeadline(action.item.caseId, action.item.id); await load(); } catch { toast.error(t('common.error')); } } else await remove(action.item); };
  const groups = state.deadlines.reduce((acc, item) => { const key = new Date(item.dueAt || item.date).toLocaleDateString(language, { dateStyle: 'full' }); (acc[key] ||= []).push(item); return acc; }, {});
  return <GlassShell active="/deadlines" title={t('cabinet.deadlines')} subtitle={`${t('cabinet.timezone')}: ${timezone}`}><Box sx={{ maxWidth: 980, mx: 'auto' }}><OfflineAlert online={online} text={t('cabinet.offline')} /><Box sx={{ display: 'flex', gap: 1, mb: 2, flexWrap: 'wrap' }}>{['overdue', 'upcoming', 'completed'].map((x) => <Button key={x} variant={filter === x ? 'contained' : 'outlined'} onClick={() => { setFilter(x); setPage(1); }}>{t(`cabinet.${x}`)}</Button>)}<PrimaryButton startIcon={<Add />} onClick={() => open()} sx={{ ml: { sm: 'auto' } }}>{t('cabinet.newDeadline')}</PrimaryButton></Box><PageState loading={state.loading} error={state.error} onRetry={load} empty={!state.deadlines.length} emptyIcon={<EventNote />} emptyTitle={t('cabinet.noDeadlines')} emptySubtitle={t('cabinet.noDeadlinesHint')}>{Object.entries(groups).map(([date, items]) => <Box component="section" key={date} sx={{ mb: 3 }}><Typography variant="h6" sx={{ mb: 1 }}>{date}</Typography>{items.map((item) => <Box key={item.id} sx={{ ...cabinetCardSx, mb: 1, display: 'flex', alignItems: { xs: 'flex-start', sm: 'center' }, flexDirection: { xs: 'column', sm: 'row' }, gap: 1 }}><Box sx={{ flex: 1 }}><Typography fontWeight={600}>{item.title}</Typography><Typography variant="body2" color="text.secondary">{formatDateTime(item.dueAt || item.date, language)} · {item.case?.title || item.caseTitle}</Typography>{item.source === 'ai' && <Chip size="small" color="warning" label={t('cabinet.aiDeadlineWarning')} sx={{ mt: 1 }} />}</Box><Box sx={{ display: 'flex', gap: .5 }}><Button aria-label={t('cabinet.complete')} startIcon={<TaskAlt />} onClick={() => setConfirmAction({ type: 'complete', item })}>{t('cabinet.complete')}</Button><Button aria-label={t('common.edit')} onClick={() => open(item)}><Edit /></Button><Button aria-label={t('common.delete')} color="error" onClick={() => setConfirmAction({ type: 'delete', item })}><Delete /></Button></Box></Box>)}</Box>)}<PagePagination page={page} totalPages={state.totalPages} onChange={setPage} label={t('cabinet.pagination')} /></PageState></Box>
    <Dialog open={dialogOpen} onClose={close} fullWidth maxWidth="sm"><DialogTitle>{editing ? t('cabinet.editDeadline') : t('cabinet.newDeadline')}</DialogTitle><DialogContent sx={{ display: 'grid', gap: 2, pt: '12px !important' }}><TextField select required label={t('cabinet.caseLabel')} value={form.caseId} onChange={(e) => setForm({ ...form, caseId: e.target.value })}>{cases.map((c) => <MenuItem value={c.id} key={c.id}>{c.title}</MenuItem>)}</TextField><TextField required label={t('cabinet.deadlineTitle')} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><TextField required type="datetime-local" label={t('cabinet.dueAt')} value={form.dueAt} onChange={(e) => setForm({ ...form, dueAt: e.target.value })} InputLabelProps={{ shrink: true }} /><TextField type="number" label={t('cabinet.reminder')} value={form.reminderMinutes} onChange={(e) => setForm({ ...form, reminderMinutes: Number(e.target.value) })} inputProps={{ min: 0, max: 525600 }} helperText={t('cabinet.reminderMinutesHint')} />{form.source === 'ai' && <Typography color="warning.main">{t('cabinet.aiDeadlineWarningLong')}</Typography>}</DialogContent><DialogActions><Button onClick={close}>{t('common.cancel')}</Button><PrimaryButton disabled={saving || !form.caseId || !form.title || !form.dueAt} onClick={save}>{t('common.save')}</PrimaryButton></DialogActions></Dialog>
    <Dialog open={!!confirmAction} onClose={() => setConfirmAction(null)} maxWidth="xs" fullWidth><DialogTitle>{confirmAction?.type === 'delete' ? t('common.delete') : t('cabinet.complete')}</DialogTitle><DialogContent><Typography>{confirmAction?.item?.title}</Typography></DialogContent><DialogActions><Button onClick={() => setConfirmAction(null)}>{t('common.cancel')}</Button><PrimaryButton color={confirmAction?.type === 'delete' ? 'error' : 'primary'} onClick={confirmMutation}>{confirmAction?.type === 'delete' ? t('common.delete') : t('cabinet.complete')}</PrimaryButton></DialogActions></Dialog>
  </GlassShell>;
};
export default DeadlinesPage;
